---
title: "Two compartment vs kinetic heterogeneity model"
author: "Ada Yan"
date: "`r Sys.Date()`"
output:
  pdf_document:
    fig_caption: TRUE
    keep_tex: yes
---

```{r global_options, include=FALSE}
knitr::opts_chunk$set(warning=FALSE, message=FALSE, echo = FALSE)
```

```{r include = FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(deSolve)
library(latex2exp)
# load R package with model fitting functions
devtools::load_all("~/git_repos/cellkineticmodels/") # change this to the directory of the git repository
# working directory should be scripts/ relative to the directory of the git repository
# i.e. the folder this vignette is in
options(mc.cores = parallel::detectCores())
rstan::rstan_options(auto_write = TRUE)
set.seed(1)
dir_name <- "two_compartment_vs_kh_files/"
if(!dir.exists(dir_name)) dir.create(dir_name)
n_compartments <- c(1.5, seq_len(6)) %>% sort()
```

```{r}
id_pars <- list(frac = 0.032, delta = 0.064, b_w = 4.18)
```

```{r}
model <- function(t, x, pars) {
  if(t < 0) {
    return(list(0))
  }
  with(as.list(c(x, pars)), {
    calc_U <- function(t) {
      if(t <= label_end) {
        U <- frac * (1 - exp(-delta * t))
      } else {
        t_shift <- t - label_end
        U <- calc_U(label_end) * exp(-delta * t_shift)
      }
      U
    }
    
    U <- calc_U(t)
    dLdt <- p * b_w * U - p * L
    
    return(list(dLdt))
  })
}

solve_label_one_pop <- function(pars) {
  yini <- c(L = 0)
  t1 <- c(seq(0, 150))
  out <- ode(yini, t1, model, pars) %>% as.data.frame %>% as_tibble
  out
}

solve_label_multi_pop <- function(pars) {
  solve_label_inner <- function(pop_idx) {
    pars$p <- pars$p[pop_idx]
    solve_label_one_pop(pars) %>%
      mutate(pop_idx = as.character(pop_idx))
  }
  out <- lapply(seq_along(pars$p), solve_label_inner) %>%
    do.call(rbind, .)
  mean_label <- out %>%
    group_by(time) %>%
    summarise(L = sum(pars[["frac_pop"]] * L)) %>%
    ungroup() %>%
    mutate(pop_idx = "mean")
  out <- bind_rows(out, mean_label)
  out
}
```


```{r}
p1_vec <- c(0.720, 0.360, .24, .12, 0.036, 0.018, 0.0072)
p2_vec <- c(0.0036, 0.016, 0.0072, 0.0108) %>% sort
alpha1_vec <- seq(.1, .9, by = .2)

sim_pars_grid <- expand_grid(p1 = p1_vec, p2 = p2_vec, alpha1 = alpha1_vec) %>%
  filter(p1 > p2) %>%
  mutate(idx = seq_len(n()))
sim_data_wrapper <- function(p1, p2, alpha1, eval = TRUE) {
  sim_filename <- paste0(dir_name, "sim_data_", num2str(p1), "_",
                         num2str(p2), "_", num2str(alpha1), "__body_water.rds")
  if(!eval) {
    return(sim_filename)
  }
  
  sim_pars <- list(p = c(p1, p2), frac_pop = c(alpha1, 1 - alpha1), label_end = 49)
  sim_pars <- c(sim_pars, id_pars, list(sigma_L = 0.005))
  
  t_vec <- seq_len(14) * 7
  sol <- solve_label_multi_pop(sim_pars)
  
  sim_data <- sol %>%
    filter(pop_idx == "mean" & time %in% t_vec) %>%
    mutate(Lhat = vnapply(L, function(x) rnorm(1, x, sim_pars$sigma_L)))
  saveRDS(list(pars = sim_pars, sol = sol, sim_data = sim_data), sim_filename)
  sim_data
}
```

```{r eval = FALSE}
invisible(Map(function(x, y, z) sim_data_wrapper(x, y, z, eval = TRUE),
              sim_pars_grid$p1, sim_pars_grid$p2, sim_pars_grid$alpha1))
```

```{r}
p1_vec <- p1_vec %>% sort
```

```{r}
fit_wrapper <- function(n_compartments, p1, p2, alpha1, prior_width, eval = TRUE) {
  sim_filename <- sim_data_wrapper(p1, p2, alpha1, eval = FALSE)
  
  if(n_compartments >= 2) {
    model_name <- paste0(n_compartments, "_compartment")
  } else if(n_compartments == 1.5){
    model_name <- "kinetic_heterogeneity"
  } else {
    model_name <- "single"
  }
  
  fit_filename <- sim_filename %>% gsub("sim_data", paste0("fit_", model_name, "_prior_width_", prior_width), .)
  if(prior_width == 1) fit_filename <- fit_filename %>% gsub(paste0("_prior_width_", prior_width), "", .)
  
  if(file.exists(fit_filename) | !eval) {
    return(fit_filename)
  }
  
  sim_data <- sim_filename %>%
    readRDS
  if(n_compartments >= 2) {
    fit_data_list <- c(list(T = nrow(sim_data$sim_data),
                            ts = sim_data$sim_data$time,
                            L = sim_data$sim_data$Lhat,
                            sigma = sim_data$pars$sigma_L,
                            n_pop = n_compartments,
                            perfect_labelling = 0,
                            prior_width = prior_width),
                       sim_data$pars[c("label_end", "delta", "frac", "b_w")])
    model <- "lymphocyte_model_fixed_U_n_compartments_variable_prior"
  } else if(n_compartments == 1.5) {
    fit_data_list <- c(list(T = nrow(sim_data$sim_data),
                            ts = sim_data$sim_data$time,
                            L = sim_data$sim_data$Lhat,
                            sigma = sim_data$pars$sigma_L,
                            prior_width = prior_width),
                       sim_data$pars[c("label_end", "delta", "frac", "b_w")])
    
    model <- "lymphocyte_model_fixed_U_b_w_variable_prior"
  } else {
    fit_data_list <- c(list(T = nrow(sim_data$sim_data),
                            ts = sim_data$sim_data$time,
                            L = sim_data$sim_data$Lhat,
                            sigma = sim_data$pars$sigma_L,
                            n_pop = n_compartments,
                            perfect_labelling = 0,
                            prior_width = prior_width),
                       sim_data$pars[c("label_end", "delta", "frac", "b_w")])
    model <- "lymphocyte_model_fixed_U_homogeneous_variable_prior"
  }
  
  fit <- fit_stan_defaults(model, fit_data_list, adapt_delta = 0.99)
  saveRDS(fit, fit_filename)
  invisible(fit)
}
```

```{r}
prior_width_vec <- c(1, 2, 5, 10)
fit_grid <- expand_grid(n_compartments = n_compartments, 
                        sim_pars_grid, 
                        prior_width = prior_width_vec, eval = TRUE) %>%
  select(-idx)
```

```{r eval = FALSE}
apply_named_args(fit_grid, 1, fit_wrapper)
```

## Fig 10 A and 10 B

```{r}
# sim_pars <- list(p = c(0.720, 0.016), frac_pop = c(0.1, 0.9), label_end = 90)

plot_p_all <- function(n_compartments_vec, prior_width) {
  get_p <- function(n_compartments) {
    fit <- fit_wrapper(n_compartments = n_compartments, 
                       p1 = 0.72,
                       p2 = 0.016,
                       alpha1 = 0.1,
                       prior_width = prior_width,
                       eval= FALSE) %>%
      readRDS
    sim_data <- sim_data_wrapper(p1 = 0.72,
                                 p2 = 0.016,
                                 alpha1 = 0.1,
                                 eval = FALSE) %>% readRDS
    
    p <- fit$fit %>% extract_fit(0, ifelse(n_compartments < 2, "p", "bar_p")) %>%
      as.data.frame %>% as_tibble %>%
      mutate(n_compartments = ifelse(n_compartments == 1.5, "implicit", n_compartments))
    if(n_compartments < 2) {
      p <- p %>% rename(bar_p = "p")
    }
    
    true_p <- sum(sim_data$pars$p * sim_data$pars$frac_pop)
    list(p = p, true_p = true_p)
  }
  
  out <- lapply(n_compartments_vec, get_p)
  
  p <- lapply(out, function(x) x$p) %>%
    do.call(rbind, .) %>%
    group_by(n_compartments) %>%
    summarise(lower = quantile(bar_p, 0.025),
              median = median(bar_p),
              upper = quantile(bar_p, 0.975)) %>%
    ungroup()
  true_p <- out[[1]]$true_p
  
  ggplot(p, aes(x = n_compartments, group = n_compartments)) +
    geom_point(aes(y = median)) +
    geom_errorbar(aes(ymin = lower, ymax = upper)) +
    geom_hline(yintercept = true_p) +
    theme_bw() +
    expand_limits(y = 0) +
    labs(color = "") +
    xlab("No. of compartments") +
    ylab("Mean proliferation rate (/day)")# +
  # labs(tag = tag1)
}
```

```{r plot_p_all, fig.width = 4, fig.height = 2.5, fig.cap = "Posterior distributions for the mean proliferation rate, for different numbers of fitted compartments, with perfect labelling and a prior for p between 0 and 1.  kh denotes fitting a model with kinetic heterogeneity.\\label{fig:plot_p_all}"}
plot_p_all(n_compartments, prior_width = 1)
```

```{r plot_p_all_wide_prior, fig.width = 4, fig.height = 2.5, fig.cap = "Posterior distributions for the mean proliferation rate, for different numbers of fitted compartments, with perfect labelling and a prior for p between 0 and 10.  kh denotes fitting a model with kinetic heterogeneity.\\label{fig:plot_p_all_wide_prior}"}
plot_p_all(seq_len(n_compartments_max), prior_width = 10)
```

```{r eval = FALSE}
get_bar_p_quantiles <- function(n_compartments, p1, p2, alpha1, prior_width) {
  fit <- fit_wrapper(n_compartments, p1, p2, alpha1, prior_width, eval = FALSE) %>%
    readRDS
  if(n_compartments >= 2) {
    bar_p_name <- "bar_p"
  } else {
    bar_p_name <- "p"
  }
  
  p <- fit$fit %>% extract_fit(0, bar_p_name, drop = TRUE)
  quantiles <- quantile(p, probs = c(0.025, 0.5, 0.975))
  bar_p <- p1 * alpha1 + p2 * (1 - alpha1)
  quantiles <- c(quantiles, bar_p > quantiles[1] && bar_p < quantiles[3],
                 quantiles[3] - quantiles[1])
  names(quantiles) <- c("lower", "median", "upper", "accurate", "range")
  quantiles
}

fit_grid <- fit_grid %>%
  select(-eval)

bar_p_quantiles <- fit_grid %>%
  filter(n_compartments <= 2) %>%
  apply_named_args(1, get_bar_p_quantiles) %>%
  do.call(rbind, .) %>%
  as_tibble %>%
  bind_cols(fit_grid) %>%
  full_join(sim_pars_grid) %>%
  mutate(bar_p_true = p1 * alpha1 + p2 * (1 - alpha1),
         rel_error = abs(median - bar_p_true) / bar_p_true * 100,
         rel_range = range / bar_p_true * 100,
         prior_width = factor(prior_width),  
         model = factor(n_compartments))
levels(bar_p_quantiles$model) <- c(1, "kh", 2)
saveRDS(bar_p_quantiles, quantiles_filename)
```

## Fig 10C and 10D

```{r error_prior_width, fig.width = 8, fig.height = 3, fig.cap = "Percentage error in the estimated proliferation rate by model and prior width."}
bar_p_quantiles %>%
  ggplot(aes(x = prior_width, y = rel_error, group = prior_width)) +
  facet_wrap(~model, nrow = 1) +
  geom_boxplot() +
  theme_bw() +
  coord_cartesian(ylim = c(0, 100)) +
  xlab(latex2exp::TeX("Prior width")) +
  ylab("Error in estimated \n mean proliferation rate (%)")
```

```{r fig.width = 8, fig.height = 3}
bar_p_quantiles %>%
  ggplot(aes(x = prior_width, y = rel_range, group = prior_width)) +
  facet_wrap(~model, nrow = 1, scales = "free") +
  geom_boxplot() +
  theme_bw() +
  xlab(latex2exp::TeX("Prior width")) +
  ylab("Width of 95% CI as \n % of true value")
```

```{r}

```

```{r}
```